### ISSUE TITLE
release 2015-03 follow-up

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#56]
### WinPython 2015-03 (2015-03-28: spyder-2.3.4, IPython-3.0, ...)

features:
- [x] starting build1: rpy2 2.5.6 in python3.4 version also
- [x] improved Julia "portable" strategy (thanks to SixString on Google Group)
- [x] remove WPPM upgrade of pip and setuptools (solves #58 , but uncorrect)
- [x] ensure pip.exe
- [x] use a more basic Python "usb" strategy
- [x] FlavorJulia with Julia kernel (on Julia 0.3.5) 
- [x] starting build2: ensure easy_install.exe
- [x] Pandas 0.16.0rc1
- [x] solve the db.py 0.4.1 problems
- [x] no need to tweak winpython according to what happens here https://github.com/ipython/ipython/issues/7739
- [x] starting build3: FlavorR + refresh R packages + r2_kernel (v0.1.winp01)
- [x] resolve WPPM uninstall issue
- [x] starting build4: show in WPPM the packages installed via pip command line
- [x] WPPM shows the pip version of an installed package
- [x] starting build5: Spyder 2.3.4
- [x] IRkernel, thanks to rzmq from Jan Schulz (https://github.com/JanSchulz/JanSchulz.github.io)
- [x] remove r2_kernel (that won't be maintained)
- [x] Pandas 0.16.0
- [x] Julia 0.3.7 +  refresh Julia package
- [x] scikit-learn 0.16.0
 
Infrastructure:
- [x] revamp the Release part of the website to make it smaller
- [x] r2 kernel experiment (but sort of by hand: using "python setup.py install" https://github.com/takluyver/r2_kernel/issues/1#issuecomment-77938909 )
- [x] update WPPM wiki pages to reflect recent changes (wheels, pip)
- [x] check what allows this https://twitter.com/caleb_hattingh/status/580207065697640448

further:
- look how-to rebuild spyder sphinx doc.
- no Ipython 3.1 yet (announced march 27th, then puff)
- considering what should be relative to  ['HOME'] instead of ['WINPYDIR']
- look at new mingw-static toolchain for python
- performance: opencl, pyspark, pyimpala, blaze, dask
- broadening: other usefull kernel with magic,
- cloud building next step
- a deep learning Flavor following Nate Diamond experience ? https://groups.google.com/forum/#!topic/deep-q-learning/K8YB17JVMHE     http://stackoverflow.com/questions/28971264/pyximport-build-errors
      (to investigate https://github.com/spragunr/deep_q_rl 
      (but pylearn2 need Theano dev version https://groups.google.com/forum/#!topic/pylearn-dev/zZqck9CRZR4)

### release (2015-03-28)
MD5 | SHA-1 | Binary
----------|------------|------------
26d6b06df3fc37fa0baca26a9b8514da | 8785906c6ea4d0dafa95c5fe19d7fbbc9669f378 | winpython-32bit-3.4.3.2.exe
a578f8adbae6a132a05d6c7797f7d897 | b7b6110a9e46caca96e25a5f8319e95a8f0e8d62 | winpython-64bit-3.4.3.2.exe
55ee26b16069c1271a10c6d89c818978 | 68e2f9d441abe751080f310bad03606cb6bb65d7 | winpython-32bit-2.7.9.4.exe
8bf63304ee520a9ac4fef9f778d3d05b | b3f35efc3d97306de211ba87a0f216fe0a31e72e | winpython-64bit-2.7.9.4.exe
8bdfe63fe8ffb72dc7e6403c219c0735 | 57f146b6d2a9adf475d2853c994d6ad1f0a9d1f0 | winpython-32bit-3.3.5.7.exe
3866f3129954a8a1e5b6e7420a12b3c9 | d8c45ddde9dd247dd9f2643ecf2caa456246b9d6 | winpython-64bit-3.3.5.7.exe
8d2f43f909282a3599450e433559550a | f829ecbbb8aa1d85568b1fabf6c8a2ee3a6eed84 | winpython-64bit-3.4.3.2flavorrfull.exe
78d201ddfe3b068070b6a227b520cc38 | 1dded6515074c1bd9b07c59af3b81e2f3761b9b4 | winpython-32bit-3.4.3.2flavorrfull.exe
a6cb717d98dc65522503e757e564323b | ab8afb8e9b13c1949a6aee412444ead25f86f080 | winpython-64bit-3.4.3.2flavorjulia.exe
3ee61d0726114b768a292245b9759334 | 6657e60ec86db414d82e92d3ec3c7b70a49c7fd9 | winpython-32bit-3.4.3.2flavorjulia.exe

Flavor Julia:

Package | Version
----------|------------
Compose | 0.3.11
IJulia | 0.2.1
Interact | 0.1.6+ | master
PyCall | 0.7.4
PyPlot | 1.5.1
SymPy | 0.2.2521 | additional | packages:
BinDeps | 0.3.8
Color | 0.4.2
Compat | 0.3.6
DataStructures | 0.3.6
Dates | 0.3.2
Docile | 0.4.7
FixedPointNumbers | 0.0.6
Graphics | 0.1.0
Iterators | 0.1.7
JSON | 0.4.1
LaTeXStrings | 0.1.2
LibExpat | 0.0.6
Nettle | 0.1.8
REPLCompletions | 0.0.3
Reactive | 0.1.10
Requires | 0.1.1
SHA | 0.0.4
URIParser | 0.0.5
WinRPM | 0.1.6
ZMQ | 0.1.17
Zlib | 0.1.7

## History of changes for WinPython 3.4.3.2

The following changes were made to WinPython distribution since version 3.4.3.1.

### Python packages

New packages:

  * [Polygon3](http://pypi.python.org/pypi/Polygon3) 3.0.7 (Polygon3 is a Python-3 package that handles polygonal shapes in 2D)

  * [PyMeta3](http://pypi.python.org/pypi/PyMeta3) 0.5.1 (Pattern-matching language based on Meta for Python 3 and 2)

  * [TTFQuery](http://pypi.python.org/pypi/TTFQuery) 1.0.5 (FontTools-based package for querying system fonts)

  * [fonttools](http://pypi.python.org/pypi/fonttools) 2.5 (Tools to manipulate font files)

  * [pybars3](http://pypi.python.org/pypi/pybars3) 0.9.1 (Handlebars.js templating for Python 3 and 2)

Upgraded packages:

  * [SQLAlchemy](http://www.sqlalchemy.org) 0.9.8 → 0.9.9 (SQL Toolkit and Object Relational Mapper)

  * [Sphinx](http://sphinx.pocoo.org) 1.2.3 → 1.3.1 (Tool for generating documentation which uses reStructuredText as its markup language)

  * [XlsxWriter](http://pypi.python.org/pypi/XlsxWriter) 0.6.6 → 0.7.1 (A Python module for creating Excel XLSX files.)

  * [astroid](http://pypi.python.org/pypi/astroid) 1.3.4 → 1.3.6 (Rebuild a new abstract syntax tree from Python's ast (required for pylint))

  * [cffi](http://pypi.python.org/pypi/cffi) 0.8.6 → 0.9.2 (Foreign Function Interface for Python calling C code.)

  * [db.py](http://pypi.python.org/pypi/db.py) 0.3.5 → 0.4.1 (a db package that doesn't suck)

  * [decorator](http://pypi.python.org/pypi/decorator) 3.4.0 → 3.4.2 (Better living through Python with decorators)

  * [ipython](http://ipython.org) 2.4.1 → 3.0.0 (Enhanced Python shell)

  * [mistune](http://pypi.python.org/pypi/mistune) 0.5 → 0.5.1 (The fastest markdown parser in pure Python, inspired by marked.)

  * [nltk](http://pypi.python.org/pypi/nltk) 3.0.1 → 3.0.2 (The Natural Language Toolkit (NLTK) is a Python package for natural language processing.)

  * [numpy](http://numpy.scipy.org/) 1.9.2rc1+mkl → 1.9.2+mkl (NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module))

  * [pandas](http://pypi.python.org/pypi/pandas) 0.15.2 → 0.16.0 (Powerful data structures for data analysis, time series and statistics)

  * [pylint](http://www.logilab.org/project/pylint) 1.4.1 → 1.4.3 (Logilab code analysis module: analyzes Python source code looking for bugs and signs of poor quality)

  * [pytz](http://pytz.sourceforge.net/) 2014.10 → 2015.2 (World Timezone Definitions for Python)

  * [requests](http://pypi.python.org/pypi/requests) 2.5.3 → 2.6.0 (Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.)

  * [rpy2](http://pypi.python.org/pypi/rpy2) 2.5.5 → 2.5.6 (Python interface to the R language (embedded R))

  * [scikit_image](http://pypi.python.org/pypi/scikit_image) 0.10.1 → 0.11.2 (Image processing toolbox for SciPy)

  * [scikit_learn](http://pypi.python.org/pypi/scikit_learn) 0.15.2 → 0.16.0 (A set of Python modules for machine learning and data mining)

  * [setuptools](http://pypi.python.org/pypi/setuptools) 12.3 → 14.3.1 (Download, build, install, upgrade, and uninstall Python packages - easily)

  * [spyder](https://bitbucket.org/spyder-ide/spyderlib) 2.3.3 → 2.3.4 (Scientific PYthon Development EnviRonment: designed for interactive computing and data visualisation with a simple and intuitive user interface)

* * *

### build5  (2015-03-24: spyder-2.3.4, pandas-0.16.0, IRkernel )

MD5 | SHA-1 | Binary
----------|------------|------------
733d5b0c5f87253f25bc518149db2e80 | 59548b4ede0363ee5cafbf8c2d0af899d94299b7 | winpython-64bit-3.4.3.2_build5_flavorrfull.exe

## History of changes for WinPython 3.4.3.2

The following changes were made to WinPython distribution since version 3.4.2.5.

### Python packages

New packages:

  * [PyMeta3](http://pypi.python.org/pypi/PyMeta3) 0.5.1 ()

  * [cffi](http://pypi.python.org/pypi/cffi) 0.9.2 (Foreign Function Interface for Python calling C code.)

  * [pybars3](http://pypi.python.org/pypi/pybars3) 0.9.1 (Handlebars.js templating for Python 3 and 2)

  * [pycparser](http://pypi.python.org/pypi/pycparser) 2.10 (C parser in Python)

Upgraded packages:

  * [Python](http://www.python.org/) 3.4.2 → 3.4.3 (Python programming language with standard library)

  * [SQLAlchemy](http://www.sqlalchemy.org) 0.9.8 → 0.9.9 (SQL Toolkit and Object Relational Mapper)

  * [XlsxWriter](http://pypi.python.org/pypi/XlsxWriter) 0.6.6 → 0.6.7 (A Python module for creating Excel XLSX files.)

  * [db.py](http://pypi.python.org/pypi/db.py) 0.3.5 → 0.4.1 (a db package that doesn't suck)

  * [ipython](http://ipython.org) 3.0.0rc1 → 3.0.0 (Enhanced Python shell)

  * [mistune](http://pypi.python.org/pypi/mistune) 0.5 → 0.5.1 (The fastest markdown parser in pure Python, inspired by marked.)

  * [nltk](http://pypi.python.org/pypi/nltk) 3.0.1 → 3.0.2 (The Natural Language Toolkit (NLTK) is a Python package for natural language processing.)

  * [numpy](http://numpy.scipy.org/) 1.9.2rc1+mkl → 1.9.2+mkl (NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module))

  * [pandas](http://pypi.python.org/pypi/pandas) 0.15.2 → 0.16.0 (Powerful data structures for data analysis, time series and statistics)

  * [pytz](http://pytz.sourceforge.net/) 2014.10 → 2015.2 (World Timezone Definitions for Python)

  * [requests](http://pypi.python.org/pypi/requests) 2.5.1 → 2.6.0 (Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.)

  * [rpy2](http://pypi.python.org/pypi/rpy2) 2.5.5 → 2.5.6 (Python interface to the R language (embedded R))

  * [scikit_image](http://pypi.python.org/pypi/scikit_image) 0.10.1 → 0.11.2 (Image processing toolbox for SciPy)

  * [setuptools](http://pypi.python.org/pypi/setuptools) 12.2 → 14.3.1 (Download, build, install, upgrade, and uninstall Python packages - easily)

  * [spyder](https://bitbucket.org/spyder-ide/spyderlib) 2.3.2 → 2.3.4 (Scientific PYthon Development EnviRonment: designed for interactive computing and data visualisation with a simple and intuitive user interface)

Removed packages:

  * [jedi](http://pypi.python.org/pypi/jedi) 0.8.1 (An autocompletion tool for Python that can be used for text editors)

* * *

### build4  (2015-03-21: rework of WPPM, to better integrate Pip)

MD5 | SHA-1 | Binary
----------|------------|------------
cf8dfd7fe96d666939dd587c3500d0e4 | 214ffee65a0edab20e16a6aaaf55731f9f0ef820 | winpython-64bit-3.4.3.2_build4.exe

## History of changes for WinPython 3.4.3.2

The following changes were made to WinPython distribution since version 3.4.3.1.

### Python packages

New packages:

  * [PyMeta3](http://pypi.python.org/pypi/PyMeta3) 0.5.1 ()

  * [pybars3](http://pypi.python.org/pypi/pybars3) 0.9.1 (Handlebars.js templating for Python 3 and 2)

Upgraded packages:

  * [SQLAlchemy](http://www.sqlalchemy.org) 0.9.8 → 0.9.9 (SQL Toolkit and Object Relational Mapper)

  * [XlsxWriter](http://pypi.python.org/pypi/XlsxWriter) 0.6.6 → 0.6.7 (A Python module for creating Excel XLSX files.)

  * [cffi](http://pypi.python.org/pypi/cffi) 0.8.6 → 0.9.2 (Foreign Function Interface for Python calling C code.)

  * [db.py](http://pypi.python.org/pypi/db.py) 0.3.5 → 0.4.1 (a db package that doesn't suck)

  * [ipython](http://ipython.org) 2.4.1 → 3.0.0 (Enhanced Python shell)

  * [mistune](http://pypi.python.org/pypi/mistune) 0.5 → 0.5.1 (The fastest markdown parser in pure Python, inspired by marked.)

  * [nltk](http://pypi.python.org/pypi/nltk) 3.0.1 → 3.0.2 (The Natural Language Toolkit (NLTK) is a Python package for natural language processing.)

  * [numpy](http://numpy.scipy.org/) 1.9.2rc1+mkl → 1.9.2+mkl (NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module))

  * [pandas](http://pypi.python.org/pypi/pandas) 0.15.2 → 0.16.0rc1 (Powerful data structures for data analysis, time series and statistics)

  * [requests](http://pypi.python.org/pypi/requests) 2.5.3 → 2.6.0 (Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.)

  * [rpy2](http://pypi.python.org/pypi/rpy2) 2.5.5 → 2.5.6 (Python interface to the R language (embedded R))

  * [scikit_image](http://pypi.python.org/pypi/scikit_image) 0.10.1 → 0.11.2 (Image processing toolbox for SciPy)

  * [setuptools](http://pypi.python.org/pypi/setuptools) 12.3 → 14.3 (Download, build, install, upgrade, and uninstall Python packages - easily)

* * *

### build3  (2015-03-16: experimental r2_kernel , updated r packages)

MD5 | SHA-1 | Binary
----------|------------|------------
7b8c64caadcf6af314430b0be4c9cd75 | d3119c4a69d3614c9b920d562aa48731c90c54e2 | winpython-64bit-3.4.3.2_build3_flavorrfull.exe

## History of changes for WinPython 3.4.3.2

The following changes were made to WinPython distribution since version 3.4.2.5.

### Python packages

New packages:

  * [PyMeta3](http://pypi.python.org/pypi/PyMeta3) 0.5.1 ()

  * [cffi](http://pypi.python.org/pypi/cffi) 0.9.2 (Foreign Function Interface for Python calling C code.)

  * [pybars3](http://pypi.python.org/pypi/pybars3) 0.8.0 (Handlebars.js templating for Python 3 and 2)

  * [pycparser](http://pypi.python.org/pypi/pycparser) 2.10 (C parser in Python)

  * [r2_kernel](http://pypi.python.org/pypi/r2_kernel) 0.1 ()

Upgraded packages:

  * [Python](http://www.python.org/) 3.4.2 → 3.4.3 (Python programming language with standard library)

  * [SQLAlchemy](http://www.sqlalchemy.org) 0.9.8 → 0.9.9 (SQL Toolkit and Object Relational Mapper)

  * [XlsxWriter](http://pypi.python.org/pypi/XlsxWriter) 0.6.6 → 0.6.7 (A Python module for creating Excel XLSX files.)

  * [db.py](http://pypi.python.org/pypi/db.py) 0.3.5 → 0.4.1 (a db package that doesn't suck)

  * [ipython](http://ipython.org) 3.0.0rc1 → 3.0.0 (Enhanced Python shell)

  * [mistune](http://pypi.python.org/pypi/mistune) 0.5 → 0.5.1 (The fastest markdown parser in pure Python, inspired by marked.)

  * [nltk](http://pypi.python.org/pypi/nltk) 3.0.1 → 3.0.2 (The Natural Language Toolkit (NLTK) is a Python package for natural language processing.)

  * [numpy](http://numpy.scipy.org/) 1.9.2rc1+mkl → 1.9.2+mkl (NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module))

  * [pandas](http://pypi.python.org/pypi/pandas) 0.15.2 → 0.16.0rc1 (Powerful data structures for data analysis, time series and statistics)

  * [requests](http://pypi.python.org/pypi/requests) 2.5.1 → 2.6.0 (Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.)

  * [rpy2](http://pypi.python.org/pypi/rpy2) 2.5.5 → 2.5.6 (Python interface to the R language (embedded R))

  * [scikit_image](http://pypi.python.org/pypi/scikit_image) 0.10.1 → 0.11.2 (Image processing toolbox for SciPy)

  * [setuptools](http://pypi.python.org/pypi/setuptools) 12.2 → 14.3 (Download, build, install, upgrade, and uninstall Python packages - easily)

  * [spyder](https://bitbucket.org/spyder-ide/spyderlib) 2.3.2 → 2.3.3 (Scientific PYthon Development EnviRonment: designed for interactive computing and data visualisation with a simple and intuitive user interface)

Removed packages:

  * [jedi](http://pypi.python.org/pypi/jedi) 0.8.1 (An autocompletion tool for Python that can be used for text editors)

* * *

### build2  (2015-03-14: improved  pandas0.16.0rc1, ...)

MD5 | SHA-1 | Binary
----------|------------|------------
0407dd49038920d1bf82cc69a2534af2 | d33ae963c088d056965951a4737d9e607430a48d  | winpython-32bit-3.4.3.2_build2.exe

## History of changes for WinPython 3.4.3.2

The following changes were made to WinPython distribution since version 3.4.3.1.

### Python packages

New packages:

  * [PyMeta3](http://pypi.python.org/pypi/PyMeta3) 0.5.1 ()

  * [pybars3](http://pypi.python.org/pypi/pybars3) 0.8.0 (Handlebars.js templating for Python 3 and 2)

Upgraded packages:

  * [SQLAlchemy](http://www.sqlalchemy.org) 0.9.8 → 0.9.9 (SQL Toolkit and Object Relational Mapper)

  * [XlsxWriter](http://pypi.python.org/pypi/XlsxWriter) 0.6.6 → 0.6.7 (A Python module for creating Excel XLSX files.)

  * [cffi](http://pypi.python.org/pypi/cffi) 0.8.6 → 0.9.2 (Foreign Function Interface for Python calling C code.)

  * [db.py](http://pypi.python.org/pypi/db.py) 0.3.5 → 0.4.1 (a db package that doesn't suck)

  * [ipython](http://ipython.org) 2.4.1 → 3.0.0 (Enhanced Python shell)

  * [mistune](http://pypi.python.org/pypi/mistune) 0.5 → 0.5.1 (The fastest markdown parser in pure Python, inspired by marked.)

  * [nltk](http://pypi.python.org/pypi/nltk) 3.0.1 → 3.0.2 (The Natural Language Toolkit (NLTK) is a Python package for natural language processing.)

  * [numpy](http://numpy.scipy.org/) 1.9.2rc1+mkl → 1.9.2+mkl (NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module))

  * [pandas](http://pypi.python.org/pypi/pandas) 0.15.2 → 0.16.0rc1 (Powerful data structures for data analysis, time series and statistics)

  * [rpy2](http://pypi.python.org/pypi/rpy2) 2.5.5 → 2.5.6 (Python interface to the R language (embedded R))

  * [scikit_image](http://pypi.python.org/pypi/scikit_image) 0.10.1 → 0.11.2 (Image processing toolbox for SciPy)

Packages no more handled via WPPM: (but still present)

  * [pip](http://pypi.python.org/pypi/pip) 6.0.8 (A tool for installing and managing Python packages)

  * [setuptools](http://pypi.python.org/pypi/setuptools) 12.3 (Download, build, install, upgrade, and uninstall Python packages - easily)

* * *

### build1 FlavorJulia (2015-03-08)

MD5 | SHA-1 | Binary
----------|------------|------------
bb93c9fa3957a75a7b82155711aea7ec | de76f8cac713e3e1fc715fbad88577f8d486fad3 | winpython-64bit-3.4.3.2_build1_flavorjulia.exe

## History of changes for WinPython 3.4.3.2

The following changes were made to WinPython distribution since version 3.4.2.5.

### Python packages

New packages:

  * [cffi](http://pypi.python.org/pypi/cffi) 0.9.1 (Foreign Function Interface for Python calling C code.)

  * [pycparser](http://pypi.python.org/pypi/pycparser) 2.10 (C parser in Python)

Upgraded packages:

  * [Python](http://www.python.org/) 3.4.2 → 3.4.3 (Python programming language with standard library)

  * [XlsxWriter](http://pypi.python.org/pypi/XlsxWriter) 0.6.6 → 0.6.7 (A Python module for creating Excel XLSX files.)

  * [ipython](http://ipython.org) 3.0.0rc1 → 3.0.0 (Enhanced Python shell)

  * [matplotlib](http://matplotlib.sourceforge.net) 1.4.3rc1 → 1.4.3 (2D plotting library (embeddable in GUIs created with PyQt))

  * [mysql_connector_python](http://pypi.python.org/pypi/mysql_connector_python) 2.0.2 → 2.0.3 (MySQL driver written in Python)

  * [numpy](http://numpy.scipy.org/) 1.9.2rc1+mkl → 1.9.2+mkl (NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module))

  * [oct2py](http://pypi.python.org/pypi/oct2py) 3.0.0 → 3.1.0 (Python to GNU Octave bridge --> run m-files from python.)

  * [pep8](http://pypi.python.org/pypi/pep8) 1.5.7 → 1.6.2 (Python style guide checker)

  * [requests](http://pypi.python.org/pypi/requests) 2.5.1 → 2.5.3 (Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.)

  * [rpy2](http://pypi.python.org/pypi/rpy2) 2.5.5 → 2.5.6 (Python interface to the R language (embedded R))

  * [scikit_image](http://pypi.python.org/pypi/scikit_image) 0.10.1 → 0.11.2 (Image processing toolbox for SciPy)

  * [spyder](https://bitbucket.org/spyder-ide/spyderlib) 2.3.2 → 2.3.3 (Scientific PYthon Development EnviRonment: designed for interactive computing and data visualisation with a simple and intuitive user interface)

  * [jedi](http://pypi.python.org/pypi/jedi) 0.8.1 (An autocompletion tool for Python that can be used for text editors)

Packages no more handled via WPPM: (but still present)

  * [pip](http://pypi.python.org/pypi/pip) 6.0.8 (A tool for installing and managing Python packages)

  * [setuptools](http://pypi.python.org/pypi/setuptools) 12.1 (Download, build, install, upgrade, and uninstall Python packages - easily)

* * *

**Comment by ankostis** [comment]
Is this the place to ask for a package to be included?

**Comment by stonebig** [comment]
why not

**Comment by ankostis** [comment]
Wrapt: a decorator-enhancing library with C Bracken's for speed:
http://wrapt.readthedocs.org/en/latest/decorators.html

Everything started with this post:
 http://blog.dscpl.com.au/2014/01/how-you-implemented-your-python.html

**Comment by stonebig** [comment]
The author doesn't publish a wheel package on pypi, and Christoph Gohlke neither.
Could he ?

**Comment by ankostis** [comment]
Left a note on that: GrahamDumpleton/wrapt#39

**Comment by stonebig** [comment]
I didn't notice it had to compile... did you try `pip install wrapt` on winpython ? does it work ?

**Comment by ankostis** [comment]
Yes, it compiled just fine (amd64).

**Comment by stonebig** [comment]
Heum, 

for R, I notice a slight discrepancy between 32 and 64 bit package versions.
That is tiny, but some users may prefer to know it:

R package | 32bit | 64bit
--------------|------------|---------
ggplot2|1.0.0|1.0.1
MASS|7.3-39|7.3-40
nnet	|7.3-9	|
rpart	|4.1-9	|
zoo|1.7-11	|1.7-12
